import type { Hotel } from '@/types/hotel';

export const HOTELS: Hotel[] = [
  {
    id: 'h1',
    name: 'Grand Luxury Palace',
    city: 'Miami',
    country: 'United States',
    rating: 4.9,
    reviews: 1482,
    price: 450,
    tag: '5-Star Hotel',
    image:
      'https://images.unsplash.com/photo-1729188430325-eb540fcdd941?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Private beach', 'Infinity pool', 'Butler service', 'Spa'],
    propertyType: 'Resort',
    distanceKm: 1.2,
    freeCancellation: true,
    payLater: true,
  },
  {
    id: 'h2',
    name: 'Amber Cove Resort',
    city: 'Male',
    country: 'Maldives',
    rating: 4.8,
    reviews: 962,
    price: 520,
    tag: 'Couple Favorite',
    image:
      'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Overwater villas', 'Floating breakfast', 'Sunset cruise', 'Spa'],
    propertyType: 'Villa',
    distanceKm: 0.6,
    freeCancellation: false,
    payLater: true,
  },
  {
    id: 'h3',
    name: 'Sunset Marina Retreat',
    city: 'Phuket',
    country: 'Thailand',
    rating: 4.7,
    reviews: 1231,
    price: 390,
    tag: 'Top Rated',
    image:
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Lagoon pool', 'Family suites', 'Gym', 'Free breakfast'],
    propertyType: 'Resort',
    distanceKm: 3.4,
    freeCancellation: true,
    payLater: false,
  },
  {
    id: 'h4',
    name: 'Emerald Hills Hideaway',
    city: 'Ubud',
    country: 'Indonesia',
    rating: 4.8,
    reviews: 856,
    price: 410,
    tag: 'Wellness',
    image:
      'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Yoga pavilion', 'Ayurveda menu', 'Spa', 'Free breakfast'],
    propertyType: 'Boutique',
    distanceKm: 2.1,
    freeCancellation: true,
    payLater: true,
  },
  {
    id: 'h5',
    name: 'Pearl Bay Residence',
    city: 'Dubai',
    country: 'United Arab Emirates',
    rating: 4.9,
    reviews: 1763,
    price: 610,
    tag: 'Skyline Views',
    image:
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Sky pool', 'Concierge', 'Gym', 'Spa'],
    propertyType: 'Hotel',
    distanceKm: 1.8,
    freeCancellation: true,
    payLater: true,
  },
  {
    id: 'h6',
    name: 'Seabreeze Vista',
    city: 'Santorini',
    country: 'Greece',
    rating: 4.8,
    reviews: 1140,
    price: 470,
    tag: 'Best Seller',
    image:
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Cliff suites', 'Sunset terraces', 'Spa', 'Airport pickup'],
    propertyType: 'Boutique',
    distanceKm: 0.9,
    freeCancellation: false,
    payLater: true,
  },
  {
    id: 'h7',
    name: 'Harborlight Suites',
    city: 'Singapore',
    country: 'Singapore',
    rating: 4.6,
    reviews: 684,
    price: 360,
    tag: 'City Escape',
    image:
      'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Sky lounge', 'Gym', 'Free breakfast', 'Airport pickup'],
    propertyType: 'Hotel',
    distanceKm: 0.5,
    freeCancellation: true,
    payLater: true,
  },
  {
    id: 'h8',
    name: 'Azure Dunes Lodge',
    city: 'Doha',
    country: 'Qatar',
    rating: 4.5,
    reviews: 492,
    price: 330,
    tag: 'Desert Chic',
    image:
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Desert tours', 'Spa', 'Rooftop bar', 'Gym'],
    propertyType: 'Resort',
    distanceKm: 4.2,
    freeCancellation: true,
    payLater: false,
  },
  {
    id: 'h9',
    name: 'Willow Creek Chalet',
    city: 'Aspen',
    country: 'United States',
    rating: 4.7,
    reviews: 578,
    price: 540,
    tag: 'Ski-In',
    image:
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Ski storage', 'Fireplace', 'Spa', 'Breakfast'],
    propertyType: 'Chalet',
    distanceKm: 2.9,
    freeCancellation: false,
    payLater: true,
  },
  {
    id: 'h10',
    name: 'Lagoon Pearl Retreat',
    city: 'Bali',
    country: 'Indonesia',
    rating: 4.6,
    reviews: 1088,
    price: 280,
    tag: 'Family Favorite',
    image:
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Kids club', 'Pool', 'Gym', 'Free breakfast'],
    propertyType: 'Resort',
    distanceKm: 3.1,
    freeCancellation: true,
    payLater: true,
  },
  {
    id: 'h11',
    name: 'Aster Court Boutique',
    city: 'Paris',
    country: 'France',
    rating: 4.7,
    reviews: 915,
    price: 490,
    tag: 'Romantic',
    image:
      'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Champagne bar', 'Airport pickup', 'Concierge', 'Spa'],
    propertyType: 'Boutique',
    distanceKm: 0.7,
    freeCancellation: true,
    payLater: false,
  },
  {
    id: 'h12',
    name: 'Nordic Harbor Hotel',
    city: 'Copenhagen',
    country: 'Denmark',
    rating: 4.4,
    reviews: 402,
    price: 310,
    tag: 'Harbor View',
    image:
      'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Sauna', 'Gym', 'Breakfast', 'Bike rental'],
    propertyType: 'Hotel',
    distanceKm: 1.1,
    freeCancellation: true,
    payLater: true,
  },
  {
    id: 'h13',
    name: 'Sapphire Dusk Villas',
    city: 'Mykonos',
    country: 'Greece',
    rating: 4.9,
    reviews: 621,
    price: 690,
    tag: 'Ultra Luxury',
    image:
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Private pool', 'Butler service', 'Spa', 'Airport pickup'],
    propertyType: 'Villa',
    distanceKm: 2.4,
    freeCancellation: false,
    payLater: true,
  },
  {
    id: 'h14',
    name: 'Coral Bay Garden',
    city: 'Sydney',
    country: 'Australia',
    rating: 4.5,
    reviews: 734,
    price: 340,
    tag: 'Garden Escape',
    image:
      'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80',
    amenities: ['Garden suites', 'Pool', 'Gym', 'Breakfast'],
    propertyType: 'Hotel',
    distanceKm: 5.1,
    freeCancellation: true,
    payLater: true,
  },
];

export const PROPERTY_TYPES = ['Hotel', 'Resort', 'Boutique', 'Villa', 'Chalet'] as const;

export const AMENITY_OPTIONS = [
  'Spa',
  'Gym',
  'Free breakfast',
  'Airport pickup',
  'Pool',
  'Private beach',
  'Concierge',
  'Butler service',
] as const;

export const CITIES = Array.from(new Set(HOTELS.map((hotel) => hotel.city)));

export const PRICE_BOUNDS = HOTELS.reduce(
  (acc, hotel) => ({
    min: Math.min(acc.min, hotel.price),
    max: Math.max(acc.max, hotel.price),
  }),
  { min: HOTELS[0].price, max: HOTELS[0].price },
);

export const HOTELS_PER_PAGE = 10;
